# For storage we are now using the AWS EBS Volumes - for that we deployed the EBS CSI Driver Add-on to our cluster

# StorageClass for AWS EBS volumes.
# The EBS CSI Driver add-on deployed in the cluster will provision the underlying EBS volumes for PVCs that use this storage class.

# Storage class allows us to define a type of storage that can be used in the cluster. And it is dynamically created as and when needed.
# Each StorageClass has a provisioner that determines what volume plugin is used for provisioning PVs.

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com       # tells Kubernetes to use the AWS EBS CSI driver to provision the EBS volumes
volumeBindingMode: WaitForFirstConsumer       # waits until the pod is scheduled, then creates the EBS volume in the correct AZ
parameters:
  type: gp3   # ebs volume type - general purpose SSD

---

# Persistent Volume Claim for MongoDB - for position tracker microservice
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi
